const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const p=require('../tools/inspect-optimizer-v2-context.cjs').contextRuntime();
for(const n of ['equipmentEffectFacets','equipmentEffectFacetCatalog','equipmentSearchSpecification'])vm.runInContext(fs.readFileSync(`src/domain/${n}.js`,'utf8'),p);
vm.runInContext(fs.readFileSync('src/optimizer-v2/facetSearch.js','utf8'),p);
const C=p.MOEOptimizerV2SearchContext,R=p.MOEOptimizerV2MetricCandidateReducer,B=p.MOEOptimizerV2BranchAndBound,original=p.catalogEquipmentToRow;
p.catalogEquipmentToRow=(i,...a)=>Object.assign(original(i,...a),i.fixtureFields||{});
const project=i=>p.MOEEquipmentEffectFacets.projectEquipmentEffectFacets(i,{toRow:p.catalogEquipmentToRow,resolveBuff:p.resolveEquipmentBuffRow,toComposite:p.equipmentBuffToCompositeRow,definitions:vm.runInContext("extraFieldDefsFor('summary')",p),effects:p.normalizeAdditionalEffects,groups:r=>p.normalizeEquipmentBuffConflictGroupsInput(r.equipBuffConflictGroups)});
const slots=['防具: 頭','装飾: 胸','武器: 右手','武器: 左手'],json=x=>JSON.parse(JSON.stringify(x));
const sort=(a,b)=>b.score-a.score||(a.key<b.key?-1:a.key>b.key?1:0),identity=v=>({score:v.score,key:v.performanceKey,ids:v.candidateIds.slice().sort()});
let states=0,violations=0,formal=0,parity=0;
for(const skill of [0,100]){
 const base=vm.runInContext('DEFAULT_STATE()',p);base.skillSim.skills['呪文抵抗力']=skill;base.composite=[{enabled:true,name:'external',extraFireRes:3,extraFireResPct:5,tags:'G',stackRule:'latest'}];
 const item=(id,slot,fields)=>({catalogId:id,name:id,category:'defense',slot,fixtureFields:fields}),buff=(id,slot,fields)=>item(id,slot,{equipBuffEnabled:true,equipBuffName:id,equipBuffTechnicId:id,...fields});
 const items=[item('flat',slots[0],{extraFireRes:30}),buff('pct',slots[0],{equipBuffExtraFireResPct:20}),buff('both',slots[0],{extraFireRes:20,equipBuffExtraFireResPct:10}),buff('G',slots[1],{equipBuffExtraFireRes:12,equipBuffExtraFireResPct:9,equipBuffConflictGroups:'G',equipBuffStackRule:'latest'}),buff('GH',slots[1],{equipBuffExtraFireRes:15,equipBuffConflictGroups:'G,H'}),buff('irrelevant-bridge',slots[1],{equipBuffFlatAttack:100,equipBuffConflictGroups:'G'}),item('req',slots[2],{extraFireRes:10,weaponDamage:60,weaponReq:[{name:'刀剣',required:100}]}),buff('shared-right',slots[2],{equipBuffExtraFireRes:8,equipBuffTechnicId:'shared',weaponDamage:20,weaponTwoHanded:'○'}),item('negative',slots[2],{extraFireRes:-30}),buff('shared-left',slots[3],{equipBuffExtraFireRes:9,equipBuffTechnicId:'shared'}),buff('H',slots[3],{equipBuffExtraFireResPct:8,equipBuffConflictGroups:'H'}),buff('negative-pct',slots[3],{equipBuffExtraFireResPct:-10})];
 const context=C.create({objective:{metric:'resistance',element:'Fire'},topK:20,slots,baseState:base}),prep=p.MOEOptimizerV2FacetSearch.prepare(items,context,{project}),r=prep.reduction,snapshot=p.MOEOptimizerV2Candidates.generate({items}),all=new Map(),partials=[];
 function visit(depth,chosen){let maximum=-Infinity;if(depth===slots.length){const e=C.evaluate(context,chosen,snapshot.sources);formal++;if(e.feasible){maximum=e.score;const d=R.describeConfiguration(r,chosen.map(c=>c.candidateId));all.set(d.performanceKey,{score:e.score,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}}
 else for(const c of [null,...snapshot.candidates.filter(c=>c.slot===slots[depth])])maximum=Math.max(maximum,visit(depth+1,c?[...chosen,c]:chosen));partials.push({depth,chosen,maximum});return maximum;}
 visit(0,[]);const expected=[...all.values()].sort(sort),members=new Map(r.contextEquivalentClasses.flatMap(c=>c.equivalentCandidateIds.map(id=>[id,c.representativeCandidateId]))),inspector=B.inspectResistance(r,slots);assert.equal(inspector.supported,true);
 for(const x of partials){if(x.chosen.some(c=>!members.has(c.candidateId)))continue;const upper=inspector.evaluate(x.chosen.map(c=>members.get(c.candidateId)),slots.slice(x.depth));assert.ok(upper>=x.maximum,JSON.stringify({upper,x}));states++;}
 for(const k of [1,5,20])for(const options of [{},{resistanceBound:false},{boundMode:'none'},{slotOrder:'ascending'},{slotOrder:'descending'}]){const ctx=C.create({objective:{metric:'resistance',element:'Fire'},topK:k,slots,baseState:base}),result=B.run({...r,context:ctx},options);assert.equal(result.diagnostics.exact,true);assert.deepEqual(json(result.results.map(identity)),json(expected.slice(0,k)));parity++;}
 const controller=B.run(r,{cooperative:true});let result;try{for(;;){const q=controller.step();if(q.done){result=q.value;break;}}}finally{controller.close();}assert.deepEqual(json(result.results.map(identity)),json(expected.slice(0,20)));assert.equal(result.diagnostics.exact,true);
 const req=snapshot.candidates.find(c=>c.catalogId==='req'),naked=C.evaluate(context,[],snapshot.sources),required=C.evaluate(context,[req],snapshot.sources);assert.equal(required.metrics.skillModInfo.mod,0);assert.equal(required.score-naked.score,10.5);
 for(const restriction of ['fixedCandidateIds','excludedCandidateIds']){const ctx=C.create({objective:{metric:'resistance',element:'Fire'},topK:5,slots,baseState:base,[restriction]:[req.candidateId]}),prepared=p.MOEOptimizerV2FacetSearch.prepare(items,ctx,{project}),oracle=new Map();
  function enumerate(depth,chosen){if(depth===slots.length){const e=C.evaluate(ctx,chosen,snapshot.sources);if(e.feasible){const d=R.describeConfiguration(prepared.reduction,chosen.map(c=>c.candidateId));oracle.set(d.performanceKey,{score:e.score,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}return;}for(const c of [null,...snapshot.candidates.filter(c=>c.slot===slots[depth])])enumerate(depth+1,c?[...chosen,c]:chosen);}
  enumerate(0,[]);const result=B.run(prepared.reduction);assert.deepEqual(json(result.results.map(identity)),json([...oracle.values()].sort(sort).slice(0,5)));assert.equal(result.diagnostics.exact,true);parity++;
 }
}
const base=vm.runInContext('DEFAULT_STATE()',p),negative={catalogId:'negative-only',name:'negative',category:'defense',slot:slots[0],fixtureFields:{extraFireRes:-10}},nullContext=C.create({objective:{metric:'resistance',element:'Fire'},slots:[slots[0]],topK:1,baseState:base}),nullPrep=p.MOEOptimizerV2FacetSearch.prepare([negative],nullContext,{project});assert.equal(B.run(nullPrep.reduction).results[0].candidateIds.length,0);
const forced={catalogId:'forced',name:'forced',category:'defense',slot:slots[0],fixtureFields:{equipBuffEnabled:true,equipBuffName:'forced',equipBuffTechnicId:'forced',equipBuffForcedEvasion:999,equipBuffExtraFireRes:1}},forcedPrep=p.MOEOptimizerV2FacetSearch.prepare([forced],nullContext,{project}),forcedResult=B.run(forcedPrep.reduction);assert.equal(forcedResult.results[0].score,1);assert.ok(B.inspectResistance(forcedPrep.reduction).evaluate([], [slots[0]])>=1);
const reverse={...negative,catalogId:'reverse',fixtureFields:{extraFireRes:-20,equipBuffEnabled:true,equipBuffName:'reverse',equipBuffExtraFireResPct:-200}},reversePrep=p.MOEOptimizerV2FacetSearch.prepare([reverse],nullContext,{project});assert.equal(B.inspectResistance(reversePrep.reduction).supported,false);assert.equal(B.run(reversePrep.reduction).results[0].score,20);
// Every element goes through the same SearchContext semantic, including race
// baseline and cross-element irrelevance. The oracle uses unreduced catalog rows.
const elements=['Fire','Water','Earth','Wind','Neutral'];
for(const element of elements){
 const flat='extra'+element+'Res',pct=flat+'Pct',buffFlat='equipBuffExtra'+element+'Res',buffPct=buffFlat+'Pct',base=vm.runInContext('DEFAULT_STATE()',p);
 base.skillSim.skills['呪文抵抗力']=100;
 const items=[{catalogId:'flat-'+element,name:'flat',category:'defense',slot:slots[0],fixtureFields:{[flat]:30,[pct]:1000}},
  {catalogId:'pct-'+element,name:'pct',category:'defense',slot:slots[0],fixtureFields:{equipBuffEnabled:true,equipBuffName:'pct',equipBuffTechnicId:'pct',[buffPct]:30}},
  {catalogId:'both-'+element,name:'both',category:'defense',slot:slots[0],fixtureFields:{[flat]:20,equipBuffEnabled:true,equipBuffName:'both',equipBuffTechnicId:'both',[buffFlat]:5,[buffPct]:10}}];
 const ctx=C.create({objective:{metric:'resistance',element},race:'cognite',baseState:base,slots:[slots[0]],topK:20}),prep=p.MOEOptimizerV2FacetSearch.prepare(items,ctx,{project}),snapshot=p.MOEOptimizerV2Candidates.generate({items}),oracle=new Map(),contextBefore=JSON.stringify(ctx);
 assert.equal(C.evaluate(ctx,[],snapshot.sources).score,110.00000000000001);
 for(const chosen of [[],...snapshot.candidates.map(c=>[c])]){const e=C.evaluate(ctx,chosen,snapshot.sources),d=R.describeConfiguration(prep.reduction,chosen.map(c=>c.candidateId));oracle.set(d.performanceKey,{score:e.score,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}
 const expected=[...oracle.values()].sort(sort),proof=B.inspectResistance(prep.reduction);assert.equal(proof.supported,true);assert.ok(proof.evaluate([],ctx.slots)>=expected[0].score);
 // Native resistance % is not in the formal base field definitions.
 assert.ok(Math.abs(C.evaluate(ctx,[snapshot.candidates.find(c=>c.catalogId==='flat-'+element)],snapshot.sources).score-140)<1e-10);
 for(const k of [1,5,20])for(const options of [{},{resistanceBound:false},{boundMode:'none'}]){const result=B.run({...prep.reduction,context:C.create({objective:{metric:'resistance',element},race:'cognite',baseState:base,slots:[slots[0]],topK:k})},options);assert.equal(result.diagnostics.exact,true);assert.deepEqual(json(result.results.map(identity)),json(expected.slice(0,k)));parity++;}
 assert.equal(JSON.stringify(ctx),contextBefore);
 const unsupported=C.create({objective:{metric:'resistance',element},secondary:'magic',baseState:base,slots:[slots[0]]});
 assert.equal(B.inspectResistance(p.MOEOptimizerV2FacetSearch.prepare(items,unsupported,{project}).reduction),null);
}
assert.ok(states>=300);const output={partialStates:states,violations,independentFormalCompletions:formal,parityRuns:parity,K:[1,5,20],elements,cooperativeParity:true,requirementEffects:true,fixedExcluded:true,slotTradeoff:true,groupsSameTechnicLatest:true,nullOptimal:true,forcedEvasionIgnored:true,negativeFactorFallback:true,nativePercentageIgnored:true,raceBaseline:true,unsupportedSecondaryFallback:true};fs.writeFileSync('docs/optimizer-v2-phase4E-fixtures.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output));
