const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const p=require('../tools/inspect-optimizer-v2-context.cjs').contextRuntime();
for(const n of ['equipmentEffectFacets','equipmentEffectFacetCatalog','equipmentSearchSpecification'])vm.runInContext(fs.readFileSync(`src/domain/${n}.js`,'utf8'),p);
vm.runInContext(fs.readFileSync('src/optimizer-v2/facetSearch.js','utf8'),p);
const C=p.MOEOptimizerV2SearchContext,R=p.MOEOptimizerV2MetricCandidateReducer,B=p.MOEOptimizerV2BranchAndBound,original=p.catalogEquipmentToRow;
p.catalogEquipmentToRow=(i,...a)=>Object.assign(original(i,...a),i.fixtureFields||{});
const project=i=>p.MOEEquipmentEffectFacets.projectEquipmentEffectFacets(i,{toRow:p.catalogEquipmentToRow,resolveBuff:p.resolveEquipmentBuffRow,toComposite:p.equipmentBuffToCompositeRow,definitions:vm.runInContext("extraFieldDefsFor('summary')",p),effects:p.normalizeAdditionalEffects,groups:r=>p.normalizeEquipmentBuffConflictGroupsInput(r.equipBuffConflictGroups)});
const slots=['防具: 頭','装飾: 胸','武器: 右手'],base=vm.runInContext('DEFAULT_STATE()',p),json=x=>JSON.parse(JSON.stringify(x));
const item=(id,slot,fields)=>({catalogId:id,name:id,category:'defense',slot,fixtureFields:{equipBuffEnabled:true,equipBuffName:id,equipBuffTechnicId:id,...fields}});
let runs=0;
function exercise(items,slots,base,extra={},options={}){const context=C.create({objective:'avoid',secondary:{metric:'resistance',element:'Fire'},topK:extra.topK||20,slots,baseState:base,...extra}),prep=p.MOEOptimizerV2FacetSearch.prepare(items,context,{project}),snapshot=p.MOEOptimizerV2Candidates.generate({items}),oracle=new Map();
function enumerate(depth,chosen){if(depth===slots.length){const e=C.evaluate(context,chosen,snapshot.sources);if(e.feasible){const d=R.describeConfiguration(prep.reduction,chosen.map(c=>c.candidateId));oracle.set(d.performanceKey,{primary:e.score,secondary:e.secondaryScore,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}return;}for(const c of [null,...snapshot.candidates.filter(c=>c.slot===slots[depth])])enumerate(depth+1,c?[...chosen,c]:chosen);}
enumerate(0,[]);const expected=[...oracle.values()].sort((a,b)=>b.primary-a.primary||b.secondary-a.secondary||(a.key<b.key?-1:a.key>b.key?1:0)).slice(0,context.topK),result=B.run(prep.reduction,options);assert.equal(result.diagnostics.exact,true);assert.deepEqual(json(result.results.map(v=>({primary:v.score,secondary:v.secondaryScore,key:v.performanceKey,ids:v.candidateIds.slice().sort()}))),json(expected));runs++;return {result,prep,snapshot,context,expected};}
const items=[item('target',slots[2],{equipBuffExtraAvoid:10,equipBuffExtraFireRes:5,equipBuffConflictGroups:'G',weaponDamage:50,weaponReq:[{name:'刀剣',required:100}]}),item('bridge',slots[0],{equipBuffFlatAttack:100,equipBuffConflictGroups:'G,H'}),item('resistance',slots[1],{equipBuffExtraFireRes:20,equipBuffConflictGroups:'H'}),item('unrelated',slots[0],{equipBuffFlatAttack:3,equipBuffConflictGroups:'Z'})];
const normal=exercise(items,slots,base),classification=normal.prep.reduction.metricReducer.classification;
assert.equal(classification.find(c=>c.candidateId.includes(':bridge:')).interaction,true);assert.equal(classification.find(c=>c.candidateId.includes(':unrelated:')).stage,'null-replaceable');
const target=normal.snapshot.candidates.find(c=>c.catalogId==='target'),naked=C.evaluate(normal.context,[],normal.snapshot.sources),required=C.evaluate(normal.context,[target],normal.snapshot.sources);assert.equal(required.metrics.skillModInfo.mod,0);assert.equal(required.score-naked.score,10);assert.equal(required.secondaryScore-naked.secondaryScore,5);
for(const k of [1,5,20])for(const field of ['fixedCandidateIds','excludedCandidateIds']){const x=exercise(items,slots,base,{topK:k,[field]:[target.candidateId]});assert.equal(x.result.diagnostics.lexicographic.enabled,true);assert.equal(x.result.diagnostics.avoidFastPath.enabled,true);assert.equal(x.result.diagnostics.resistanceFastPath.enabled,true);}
const cooperative=B.run(normal.prep.reduction,{cooperative:true});let co;try{for(;;){const q=cooperative.step();if(q.done){co=q.value;break;}}}finally{cooperative.close();}assert.deepEqual(json(co.results),json(normal.result.results));assert.equal(co.diagnostics.exact,true);
const forced=exercise([item('forced',slots[0],{equipBuffForcedEvasion:77.25,equipBuffExtraFireRes:5})],[slots[0]],base);assert.equal(forced.result.results[0].score,77.25);assert.equal(forced.result.results[0].secondaryScore,5);assert.ok(B.inspectAvoid(forced.prep.reduction).evaluate([], [slots[0]])>=77.25);
const constrained=exercise(items,slots,base,{constraints:[{metric:'avoid',op:'gte',value:0}]});assert.equal(constrained.result.diagnostics.lexicographic.enabled,false);
exercise(items,slots,base,{}, {avoidBound:false});exercise(items,slots,base,{}, {slotOrder:'ascending'});exercise(items,slots,base,{}, {slotOrder:'descending'});
// Even a tiny nonzero percentage must refuse zero-percentage certification.
// Retain the padded bound when its rounded multiplier is 1.
for(const fixed of [false,true]){const state=vm.runInContext('DEFAULT_STATE()',p);if(fixed)state.composite=[{enabled:true,name:'tiny pct',extraAvoidPct:1e-14}];const tinyItems=[item('tiny',slots[0],{extraAvoid:2e15,extraFireRes:1,...(!fixed?{equipBuffExtraAvoidPct:1e-14}:{})}),item('plain',slots[0],{extraAvoid:2e15,extraFireRes:100})];
const x=exercise(tinyItems,[slots[0]],state),ins=B.inspectAvoid(x.prep.reduction);for(const c of x.prep.reduction.candidates){const e=C.evaluate(x.context,[c],x.snapshot.sources);assert.ok(ins.evaluate([c.candidateId],[])>=e.score);}for(const k of [1,5,20])exercise(tinyItems,[slots[0]],state,{topK:k});}
const report={boundaryParityRuns:runs,fixedExcludedMultiSlot:true,cooperativeParity:true,formalRequirementBuffs:true,interactionBridge:true,disconnectedBuffRemoved:true,forcedEvasionPrimaryOnly:true,tinyPercentageSafety:true,minimumFallback:true,orderingParity:true};fs.writeFileSync('docs/optimizer-v2-phase4F-3-boundaries.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
