const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const p=require('../tools/inspect-optimizer-v2-context.cjs').contextRuntime();
for(const n of ['equipmentEffectFacets','equipmentEffectFacetCatalog','equipmentSearchSpecification'])vm.runInContext(fs.readFileSync(`src/domain/${n}.js`,'utf8'),p);
vm.runInContext(fs.readFileSync('src/optimizer-v2/facetSearch.js','utf8'),p);
const C=p.MOEOptimizerV2SearchContext,R=p.MOEOptimizerV2MetricCandidateReducer,B=p.MOEOptimizerV2BranchAndBound,original=p.catalogEquipmentToRow;
p.catalogEquipmentToRow=(i,...a)=>Object.assign(original(i,...a),i.fixtureFields||{});
const project=i=>p.MOEEquipmentEffectFacets.projectEquipmentEffectFacets(i,{toRow:p.catalogEquipmentToRow,resolveBuff:p.resolveEquipmentBuffRow,toComposite:p.equipmentBuffToCompositeRow,definitions:vm.runInContext("extraFieldDefsFor('summary')",p),effects:p.normalizeAdditionalEffects,groups:r=>p.normalizeEquipmentBuffConflictGroupsInput(r.equipBuffConflictGroups)});
const slots=['防具: 頭','装飾: 胸','武器: 右手'],json=x=>JSON.parse(JSON.stringify(x)),compare=(a,b)=>b.primary-a.primary||b.secondary-a.secondary||(a.key<b.key?-1:a.key>b.key?1:0);
let states=0,formal=0,parity=0,secondaryCalls=0;
function exercise(element,items,base,activeSlots=slots,extra={}){
 const context=C.create({objective:'magic',secondary:{metric:'resistance',element},topK:20,slots:activeSlots,baseState:base,...extra}),prep=p.MOEOptimizerV2FacetSearch.prepare(items,context,{project}),r=prep.reduction,snapshot=p.MOEOptimizerV2Candidates.generate({items}),oracle=new Map(),records=[];
 function visit(depth,chosen){let best=null,maxResistance=-Infinity;if(depth===activeSlots.length){formal++;const e=C.evaluate(context,chosen,snapshot.sources);if(e.feasible){const d=R.describeConfiguration(r,chosen.map(c=>c.candidateId));best={primary:e.score,secondary:e.secondaryScore,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()};oracle.set(best.key,best);maxResistance=e.secondaryScore;}}
 else for(const c of [null,...snapshot.candidates.filter(c=>c.slot===activeSlots[depth])]){const child=visit(depth+1,c?[...chosen,c]:chosen);if(child.best&&(!best||compare(child.best,best)<0))best=child.best;maxResistance=Math.max(maxResistance,child.maxResistance);}records.push({depth,chosen,best,maxResistance});return {best,maxResistance};}
 visit(0,[]);const expected=[...oracle.values()].sort(compare),members=new Map(r.contextEquivalentClasses.flatMap(c=>c.equivalentCandidateIds.map(id=>[id,c.representativeCandidateId]))),primary=B.inspectMagicPrimary(r,activeSlots),secondary=B.inspectResistance(r,activeSlots);
 if(!extra.fixedCandidateIds&&!extra.excludedCandidateIds&&!extra.constraints){assert.ok(r.metricReducer.applied);assert.ok(secondary.supported);
 for(const x of records){if(x.chosen.some(c=>!members.has(c.candidateId)))continue;const ids=x.chosen.map(c=>members.get(c.candidateId)),remaining=activeSlots.slice(x.depth),M=primary.evaluate(ids,remaining),Q=secondary.evaluate(ids,remaining);if(x.best&&M!==null&&Q!==null){assert.ok(M>=x.best.primary,JSON.stringify({M,best:x.best}));assert.ok(Q>=x.maxResistance);assert.ok(M>x.best.primary||M===x.best.primary&&Q>=x.best.secondary);states++;}}}
 for(const k of [1,5,20])for(const options of [{},{boundMode:'none'},{resistanceBound:false},{lexicographicFastPath:false}]){const ctx=C.create({objective:'magic',secondary:{metric:'resistance',element},topK:k,slots:activeSlots,baseState:base,...extra}),result=B.run({...r,context:ctx},options);assert.equal(result.diagnostics.exact,true);if(!Object.keys(options).length)assert.equal(result.diagnostics.lexicographic.enabled,!extra.fixedCandidateIds&&!extra.excludedCandidateIds&&!extra.constraints);secondaryCalls+=result.diagnostics.lexicographic.secondaryCalls;
 const actual=result.results.map((v,i)=>{assert.equal(v.rankScore,v.score);assert.equal(v.secondaryRankScore,v.secondaryScore);return {primary:v.score,secondary:v.secondaryScore,key:v.performanceKey,ids:v.candidateIds.slice().sort(),rank:i+1};});assert.deepEqual(json(actual),json(expected.slice(0,k).map((v,i)=>({...v,rank:i+1}))));parity++;}
 return {expected,prep,snapshot,context};
}
for(const element of ['Fire','Water','Earth','Wind','Neutral'])for(const percent of [0,7]){
 const base=vm.runInContext('DEFAULT_STATE()',p);base.composite=[{enabled:true,name:'external',flatMagic:3,['extra'+element+'Res']:2,tags:'G'}];if(percent)base.pct=[{enabled:true,target:'magic',percent}];
 const item=(id,slot,fields)=>({catalogId:id,name:id,category:'defense',slot,fixtureFields:fields}),buff=(id,slot,fields)=>item(id,slot,{equipBuffEnabled:true,equipBuffName:id,equipBuffTechnicId:id,...fields});
 const items=slots.flatMap((slot,i)=>[buff('high'+i,slot,{magic:20,['extra'+element+'Res']:2,equipBuffFlatMagic:2,['equipBuffExtra'+element+'Res']:3,weaponDamage:50,weaponReq:[{name:'刀剣',required:100}]}),buff('equal'+i,slot,{magic:22,['extra'+element+'Res']:8,equipBuffConflictGroups:'G',equipBuffFlatMagic:0,equipBuffFlatAttack:100}),buff('res'+i,slot,{magic:10,['extra'+element+'Res']:100,['equipBuffExtra'+element+'ResPct']:15,equipBuffConflictGroups:'G,H',equipBuffTechnicId:'shared'}),buff('negative'+i,slot,{magic:-20,['extra'+element+'Res']:-10,equipBuffMagicPct:i===1?20:0,equipBuffForcedEvasion:999,equipBuffTechnicId:i===2?'shared':'negative'+i})]);
 const {snapshot,context}=exercise(element,items,base);const req=snapshot.candidates.find(c=>c.catalogId==='high2'),naked=C.evaluate(context,[],snapshot.sources),required=C.evaluate(context,[req],snapshot.sources);assert.equal(required.metrics.skillModInfo.mod,0);assert.ok(Math.abs(required.score-naked.score-22*(1+percent/100))<1e-10);assert.equal(required.secondaryScore-naked.secondaryScore,5);
}
const nearBase=vm.runInContext('DEFAULT_STATE()',p),near=exercise('Fire',[{catalogId:'near-low',name:'near-low',category:'defense',slot:slots[0],fixtureFields:{magic:1,extraFireRes:1000}},{catalogId:'near-high',name:'near-high',category:'defense',slot:slots[0],fixtureFields:{magic:1+1e-12,extraFireRes:0}}],nearBase,[slots[0]]);assert.equal(near.expected[0].primary,1+1e-12);
const negativeBase=vm.runInContext('DEFAULT_STATE()',p);negativeBase.pct=[{enabled:true,target:'magic',percent:-200}];exercise('Water',[{catalogId:'negative-factor',name:'negative-factor',category:'defense',slot:slots[0],fixtureFields:{magic:-10,extraWaterRes:5}},{catalogId:'positive-body',name:'positive-body',category:'defense',slot:slots[0],fixtureFields:{magic:20,extraWaterRes:100}}],negativeBase,[slots[0]]);
const base=vm.runInContext('DEFAULT_STATE()',p),levels=Array.from({length:22},(_,i)=>({catalogId:'level'+i,name:'level'+i,category:'defense',slot:slots[0],fixtureFields:{magic:i<19?100:99,extraFireRes:i<19?i:1000+i}}));
const top=exercise('Fire',levels,base,[slots[0]]).expected;assert.equal(top.slice(0,20).filter(x=>x.primary===100).length,19);assert.equal(top[19].primary,99);assert.ok(top[0].secondary<top[19].secondary);
const snapshot=p.MOEOptimizerV2Candidates.generate({items:levels});for(const field of ['fixedCandidateIds','excludedCandidateIds'])exercise('Fire',levels,base,[slots[0]],{[field]:[snapshot.candidates[0].candidateId]});
exercise('Fire',levels,base,[slots[0]],{constraints:[{metric:'magic',op:'gte',value:0}]});
const nullTop=exercise('Fire',[{catalogId:'negative-only',name:'negative',category:'defense',slot:slots[0],fixtureFields:{magic:-1,extraFireRes:100}}],base,[slots[0]]).expected;assert.equal(nullTop[0].ids.length,0);
assert.ok(states>=300);assert.ok(secondaryCalls>0);const report={partialStates:states,violations:0,independentFormalCompletions:formal,parityRuns:parity,K:[1,5,20],elements:['Fire','Water','Earth','Wind','Neutral'],primaryMaximum19:true,formalRequirements:true,conflicts:true,slotTradeoff:true,null:true,fixedExcludedFallback:true,minimumFallback:true,explicitRanksAndIds:true,secondaryCalls};fs.writeFileSync('docs/optimizer-v2-phase4F-2-fixtures.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
