const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const p=require('../tools/inspect-optimizer-v2-context.cjs').contextRuntime();
for(const n of ['equipmentEffectFacets','equipmentEffectFacetCatalog','equipmentSearchSpecification'])vm.runInContext(fs.readFileSync(`src/domain/${n}.js`,'utf8'),p);
vm.runInContext(fs.readFileSync('src/optimizer-v2/facetSearch.js','utf8'),p);
const C=p.MOEOptimizerV2SearchContext,R=p.MOEOptimizerV2MetricCandidateReducer,B=p.MOEOptimizerV2BranchAndBound,original=p.catalogEquipmentToRow;
p.catalogEquipmentToRow=(i,...a)=>Object.assign(original(i,...a),i.fixtureFields||{});
const project=i=>p.MOEEquipmentEffectFacets.projectEquipmentEffectFacets(i,{toRow:p.catalogEquipmentToRow,resolveBuff:p.resolveEquipmentBuffRow,toComposite:p.equipmentBuffToCompositeRow,definitions:vm.runInContext("extraFieldDefsFor('summary')",p),effects:p.normalizeAdditionalEffects,groups:r=>p.normalizeEquipmentBuffConflictGroupsInput(r.equipBuffConflictGroups)});
const slots=['防具: 頭','装飾: 胸','武器: 右手','武器: 左手'],json=x=>JSON.parse(JSON.stringify(x));
const sort=(a,b)=>b.score-a.score||(a.key<b.key?-1:a.key>b.key?1:0),identity=v=>({score:v.score,key:v.performanceKey,ids:v.candidateIds.slice().sort()});
let states=0,violations=0,formal=0,parity=0;
for(const skill of [0,100]){
 const base=vm.runInContext('DEFAULT_STATE()',p);base.skillSim.skills['攻撃回避']=skill;base.composite=[{enabled:true,name:'external',extraAvoid:3,extraAvoidPct:5,tags:'G',stackRule:'latest'}];
 const item=(id,slot,fields)=>({catalogId:id,name:id,category:'defense',slot,fixtureFields:fields}),buff=(id,slot,fields)=>item(id,slot,{equipBuffEnabled:true,equipBuffName:id,equipBuffTechnicId:id,...fields});
 const items=[item('flat',slots[0],{extraAvoid:30}),buff('pct',slots[0],{equipBuffExtraAvoidPct:20}),buff('both',slots[0],{extraAvoid:20,equipBuffExtraAvoidPct:10}),buff('G',slots[1],{equipBuffExtraAvoid:12,equipBuffExtraAvoidPct:9,equipBuffConflictGroups:'G',equipBuffStackRule:'latest'}),buff('GH',slots[1],{equipBuffExtraAvoid:15,equipBuffConflictGroups:'G,H'}),buff('irrelevant-bridge',slots[1],{equipBuffFlatAttack:100,equipBuffConflictGroups:'G'}),item('req',slots[2],{extraAvoid:10,weaponDamage:60,weaponReq:[{name:'刀剣',required:100}]}),buff('shared-right',slots[2],{equipBuffExtraAvoid:8,equipBuffTechnicId:'shared',weaponDamage:20,weaponTwoHanded:'○'}),item('negative',slots[2],{extraAvoid:-30}),buff('shared-left',slots[3],{equipBuffExtraAvoid:9,equipBuffTechnicId:'shared'}),buff('H',slots[3],{equipBuffExtraAvoidPct:8,equipBuffConflictGroups:'H'}),buff('negative-pct',slots[3],{equipBuffExtraAvoidPct:-10})];
 const context=C.create({objective:'avoid',topK:20,slots,baseState:base}),prep=p.MOEOptimizerV2FacetSearch.prepare(items,context,{project}),r=prep.reduction,snapshot=p.MOEOptimizerV2Candidates.generate({items}),all=new Map(),partials=[];
 function visit(depth,chosen){let maximum=-Infinity;if(depth===slots.length){const e=C.evaluate(context,chosen,snapshot.sources);formal++;if(e.feasible){maximum=e.score;const d=R.describeConfiguration(r,chosen.map(c=>c.candidateId));all.set(d.performanceKey,{score:e.score,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}}
 else for(const c of [null,...snapshot.candidates.filter(c=>c.slot===slots[depth])])maximum=Math.max(maximum,visit(depth+1,c?[...chosen,c]:chosen));partials.push({depth,chosen,maximum});return maximum;}
 visit(0,[]);const expected=[...all.values()].sort(sort),members=new Map(r.contextEquivalentClasses.flatMap(c=>c.equivalentCandidateIds.map(id=>[id,c.representativeCandidateId]))),inspector=B.inspectAvoid(r,slots);assert.equal(inspector.supported,true);
 for(const x of partials){if(x.chosen.some(c=>!members.has(c.candidateId)))continue;const upper=inspector.evaluate(x.chosen.map(c=>members.get(c.candidateId)),slots.slice(x.depth));assert.ok(upper>=x.maximum,JSON.stringify({upper,x}));states++;}
 for(const k of [1,5,20])for(const options of [{},{avoidBound:false},{boundMode:'none'},{slotOrder:'ascending'},{slotOrder:'descending'}]){const ctx=C.create({objective:'avoid',topK:k,slots,baseState:base}),result=B.run({...r,context:ctx},options);assert.equal(result.diagnostics.exact,true);assert.deepEqual(json(result.results.map(identity)),json(expected.slice(0,k)));parity++;}
 const controller=B.run(r,{cooperative:true});let result;try{for(;;){const q=controller.step();if(q.done){result=q.value;break;}}}finally{controller.close();}assert.deepEqual(json(result.results.map(identity)),json(expected.slice(0,20)));assert.equal(result.diagnostics.exact,true);
 const req=snapshot.candidates.find(c=>c.catalogId==='req'),naked=C.evaluate(context,[],snapshot.sources),required=C.evaluate(context,[req],snapshot.sources);assert.equal(required.metrics.skillModInfo.mod,0);assert.equal(required.score-naked.score,10.5);
 for(const restriction of ['fixedCandidateIds','excludedCandidateIds']){const ctx=C.create({objective:'avoid',topK:5,slots,baseState:base,[restriction]:[req.candidateId]}),prepared=p.MOEOptimizerV2FacetSearch.prepare(items,ctx,{project}),oracle=new Map();
  function enumerate(depth,chosen){if(depth===slots.length){const e=C.evaluate(ctx,chosen,snapshot.sources);if(e.feasible){const d=R.describeConfiguration(prepared.reduction,chosen.map(c=>c.candidateId));oracle.set(d.performanceKey,{score:e.score,key:d.performanceKey,ids:d.equipment.map(x=>x.selectedCandidate.candidateId).sort()});}return;}for(const c of [null,...snapshot.candidates.filter(c=>c.slot===slots[depth])])enumerate(depth+1,c?[...chosen,c]:chosen);}
  enumerate(0,[]);const result=B.run(prepared.reduction);assert.deepEqual(json(result.results.map(identity)),json([...oracle.values()].sort(sort).slice(0,5)));assert.equal(result.diagnostics.exact,true);parity++;
 }
}
const base=vm.runInContext('DEFAULT_STATE()',p),negative={catalogId:'negative-only',name:'negative',category:'defense',slot:slots[0],fixtureFields:{extraAvoid:-10}},nullContext=C.create({objective:'avoid',slots:[slots[0]],topK:1,baseState:base}),nullPrep=p.MOEOptimizerV2FacetSearch.prepare([negative],nullContext,{project});assert.equal(B.run(nullPrep.reduction).results[0].candidateIds.length,0);
const forced={catalogId:'forced',name:'forced',category:'defense',slot:slots[0],fixtureFields:{equipBuffEnabled:true,equipBuffName:'forced',equipBuffTechnicId:'forced',equipBuffForcedEvasion:999,equipBuffExtraAvoid:1}},forcedPrep=p.MOEOptimizerV2FacetSearch.prepare([forced],nullContext,{project}),forcedResult=B.run(forcedPrep.reduction);assert.equal(forcedResult.results[0].score,999);assert.ok(B.inspectAvoid(forcedPrep.reduction).evaluate([], [slots[0]])>=999);
const reverse={...negative,catalogId:'reverse',fixtureFields:{extraAvoid:-20,equipBuffEnabled:true,equipBuffName:'reverse',equipBuffExtraAvoidPct:-200}},reversePrep=p.MOEOptimizerV2FacetSearch.prepare([reverse],nullContext,{project});assert.equal(B.inspectAvoid(reversePrep.reduction).supported,false);assert.equal(B.run(reversePrep.reduction).results[0].score,20);
assert.ok(states>=300);const output={partialStates:states,violations,independentFormalCompletions:formal,parityRuns:parity,K:[1,5,20],cooperativeParity:true,requirementEffects:true,fixedExcluded:true,slotTradeoff:true,groupsSameTechnicLatest:true,nullOptimal:true,forcedEvasion:true,negativeFactorFallback:true};fs.writeFileSync('docs/optimizer-v2-phase4D-fixtures.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output));
