const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),cp=require('node:child_process');
function runtime(legacy=false){const p=require('../tools/inspect-optimizer-v2-context.cjs').contextRuntime();for(const n of ['equipmentEffectFacets','equipmentEffectFacetCatalog','equipmentSearchSpecification'])vm.runInContext(fs.readFileSync(`src/domain/${n}.js`,'utf8'),p);for(const n of ['candidates','evaluationSession','effectiveCandidates','metricCandidateReducer','facetSearch'])vm.runInContext(legacy?cp.execFileSync('git',['show',`0d9c682:src/optimizer-v2/${n}.js`],{encoding:'utf8'}):fs.readFileSync(`src/optimizer-v2/${n}.js`,'utf8'),p);const original=p.catalogEquipmentToRow;p.catalogEquipmentToRow=(i,...a)=>Object.assign(original(i,...a),i.fixtureFields||{});return p;}
const current=runtime(),legacy=runtime(true),slots=['防具: 頭','装飾: 胸','武器: 右手'];
const item=(id,slot,fields)=>({catalogId:id,name:id,slot,category:'defense',fixtureFields:fields});
const items=[item('flat',slots[0],{extraAvoid:20}),item('percent',slots[0],{equipBuffEnabled:true,equipBuffName:'pct',equipBuffExtraAvoidPct:10}),item('mixed',slots[0],{extraAvoid:10,equipBuffEnabled:true,equipBuffName:'mixed',equipBuffExtraAvoidPct:5}),item('buff',slots[1],{equipBuffEnabled:true,equipBuffName:'group',equipBuffExtraAvoid:15,equipBuffConflictGroups:'G'}),item('bridge',slots[1],{equipBuffEnabled:true,equipBuffName:'bridge',equipBuffFlatAttack:40,equipBuffConflictGroups:'G'}),item('requirement',slots[2],{weaponDamage:60,weaponReq:[{name:'刀剣',required:100}],extraAvoid:9}),item('negative',slots[2],{extraAvoid:-10})];
const id='ov2:catalogId:requirement:quality:raw';
const identity=r=>JSON.parse(JSON.stringify({exact:r.diagnostics.exact,top:r.results.map((x,i)=>({rank:i+1,score:x.score,key:x.performanceKey,ids:x.candidateIds.slice().sort()}))}));
function prepare(p,k,variant,options){const base=vm.runInContext('DEFAULT_STATE()',p);if(variant==='skill')base.skillSim.skills['攻撃回避']=100;if(variant==='external')base.composite=[{enabled:true,name:'external',extraAvoid:12,extraAvoidPct:5,tags:'G',stackRule:'latest'}];const context=p.MOEOptimizerV2SearchContext.create({objective:'avoid',slots,topK:k,baseState:base,...(variant==='fixed'?{fixedCandidateIds:[id]}:{}),...(variant==='excluded'?{excludedCandidateIds:[id]}:{})});return p.MOEOptimizerV2FacetSearch.prepare(items,context,options);}
let parity=0;
for(const variant of ['default','skill','fixed','excluded','external'])for(const k of [1,5,20]){
 const old=prepare(legacy,k,variant),cold=prepare(current,k,variant),warm=prepare(current,k,variant),off=prepare(current,k,variant,{candidateCache:false});const expected=identity(legacy.MOEOptimizerV2BranchAndBound.run(old.reduction));
 for(const prepared of [cold,warm,off]){assert.deepEqual(identity(current.MOEOptimizerV2BranchAndBound.run(prepared.reduction)),expected);parity++;}
 assert.ok(warm.diagnostics.catalogCache.candidateHits>0);assert.equal(warm.diagnostics.catalogCache.candidateMisses,0);assert.equal(warm.reduction.candidatePreparation.diagnostics.artifactBuildCount,0);assert.equal(warm.reduction.candidatePreparation.diagnostics.buffBuildCount,0);
 const candidate=warm.snapshot.candidates[0],store=warm.reduction.candidatePreparation,canonical=store.readRow(candidate),before=JSON.stringify(canonical),copy=store.rowFor(candidate);copy.extraAvoid=999;copy.extraEffects.push({key:'skillPlus',name:'破壊魔法',value:999});assert.equal(JSON.stringify(canonical),before);assert.ok(Object.isFrozen(canonical));assert.ok(Object.isFrozen(candidate));
 const projection=current.MOEOptimizerV2EffectiveCandidates.project(candidate,warm.snapshot.sources[candidate.sourceRef],warm.reduction.context,{candidatePreparation:store});assert.ok(Object.isFrozen(projection));assert.throws(()=>projection.protectedReasons.push('pollution'),/extensible|read only|Cannot add/);
 const other=prepare(current,k,variant);assert.throws(()=>current.MOEOptimizerV2EffectiveCandidates.project(candidate,warm.snapshot.sources[candidate.sourceRef],other.reduction.context,{candidatePreparation:store}),/context mismatch/);
}
// Same identity with changed item contents must not reuse the old catalog row.
const changed=JSON.parse(JSON.stringify(items));changed[0].fixtureFields.extraAvoid=77;const ctx=current.MOEOptimizerV2SearchContext.create({objective:'avoid',slots,topK:1});const rebuilt=current.MOEOptimizerV2FacetSearch.prepare(changed,ctx);assert.equal(rebuilt.snapshot.candidates.find(c=>c.catalogId==='flat').evaluationFields.extraAvoid,77);
// Runtime knowledge changes invalidate immutable normalization/Buff inputs.
const before=prepare(current,1,'default');current.MOE_BUFF_RULES_MANUAL={...current.MOE_BUFF_RULES_MANUAL,'cache-test':{name:'cache-test',flatMagic:1}};const after=prepare(current,1,'default');assert.ok(after.diagnostics.catalogCache.misses>0);assert.ok(after.reduction.candidatePreparation.diagnostics.sharedRowMisses>0);assert.notEqual(before.snapshot.catalogCacheSignature,after.snapshot.catalogCacheSignature);
current.MOE_BUFF_RULES_MANUAL={'nonfinite':{value:NaN}};const unsafeA=current.MOEOptimizerV2Candidates.createCatalogPreparation();current.MOE_BUFF_RULES_MANUAL={'nonfinite':{value:Infinity}};const unsafeB=current.MOEOptimizerV2Candidates.createCatalogPreparation();assert.notEqual(unsafeA.signature,unsafeB.signature);
console.log(JSON.stringify({checkpoint:'0d9c682',topKParity:parity,K:[1,5,20],contexts:['default','skillSim','fixed','excluded','external'],mutationSafety:true,itemInvalidation:true,runtimeInvalidation:true,contextIdentityGuard:true}));
