/* Equipment-only pet growth model. Source: supplied pet-equipment table A-M.
 * Same class contributes once; independent classes multiply. No consumables/BRE.
 * Resolver uses strongest effect, like existing composite competition scoring.
 */
(function(global){
 const definitions=[['A',1.1,[7956,10469,9936]],['A',1.2,[13390]],['B',1.1,[8305,10678]],['B',1.2,[13692]],['C',1.1,[9151,10865,11534]],['D',1.1,[10304,11784]],['D',1.05,[13691]],['E',1.1,[10510]],['F',1.05,[11323,11966]],['F',1.1,[12207]],['G',1.2,[12388,13284]],['H',1.1,[12612]],['H',1.2,[13616]],['I',1.1,[11653]],['I',1.2,[13485]],['J',1.05,[13041]],['K',1.1,[13787]],['L',1.2,[14655]],['M',1.1,[14656]]];
 const rules=Object.freeze(Object.fromEntries(definitions.flatMap(([group,multiplier,ids])=>ids.map(id=>[id,Object.freeze({group,multiplier})]))));
 function rule(row){if(!row?.enabled||row.excluded||!row.equipBuffEnabled)return null;return rules[String(row.equipBuffTechnicId||'').replace(/^technic-/,'')]||null;}
 function resolve(rows){const groups={};for(const row of rows){const r=rule(row);if(r)groups[r.group]=Math.max(groups[r.group]||1,r.multiplier);}let multiplier=1;for(const group of Object.keys(groups).sort())multiplier*=groups[group];return {multiplier,groups,scope:'装備による成長率補正。同分類は最大補正1つを採用（BRE・消耗品・ペットへの技は含まない）'};}
 function prepareBound(plan){const byId=new Map([...plan.rows].map(([id,row])=>[id,rule(row)])),suffix=Array(plan.slots.length+1);suffix[plan.slots.length]={};for(let d=plan.slots.length-1;d>=0;d--){const g={...suffix[d+1]};for(const cls of plan.groups.get(plan.slots[d])){const r=byId.get(cls.representativeCandidateId);if(r)g[r.group]=Math.max(g[r.group]||1,r.multiplier);}suffix[d]=g;}const names=[...new Set([...byId.values()].filter(Boolean).map(r=>r.group))].sort(),indexes=new Map(names.map((n,i)=>[n,i])),count=1<<names.length,weights=names.map(n=>Math.max(...[...byId.values()].filter(r=>r?.group===n).map(r=>r.multiplier))),dp=Array(plan.slots.length+1);dp[plan.slots.length]=new Float64Array(count);for(let mask=0;mask<count;mask++){let v=1;for(let i=0;i<names.length;i++)if(mask&(1<<i))v*=weights[i];dp[plan.slots.length][mask]=v;}for(let d=plan.slots.length-1;d>=0;d--){const next=dp[d+1],current=new Float64Array(count),bits=[...new Set(plan.groups.get(plan.slots[d]).map(c=>byId.get(c.representativeCandidateId)).filter(Boolean).map(r=>1<<indexes.get(r.group)))];for(let mask=0;mask<count;mask++){let v=next[mask];for(const bit of bits)v=Math.max(v,next[mask|bit]);current[mask]=v;}dp[d]=current;}return {byId,suffix,dp,indexes};}
 function upper(proof,ids,depth){const groups={...proof.suffix[depth]};for(const id of ids){const r=proof.byId.get(id);if(r)groups[r.group]=Math.max(groups[r.group]||1,r.multiplier);}let value=1;for(const g of Object.keys(groups).sort())value*=groups[g];let mask=0;for(const id of ids){const r=proof.byId.get(id);if(r)mask|=1<<proof.indexes.get(r.group);}return Math.min(value,proof.dp[depth][mask]);}
 function* prepareSteps(items,context){
  if(context.secondary||context.mainWeaponSkill||context.mainWeaponSlot||context.constraints.some(c=>c.metric.metric!=='petGrowth'))throw Error('ペット成長率の構成計算は単独軸・成長率の最低値に対応しています。');
  if(context.fixedCandidateIds.some(id=>context.excludedCandidateIds.includes(id)))throw Error('同じ装備を固定と除外の両方に指定できません。');
  const selected=[],fixed=new Set(context.fixedCandidateIds);let n=0;
  for(const item of items){yield {phase:'catalog',processed:n++,total:items.length};const id=Number(String(item.technicId||item.buffRefs?.[0]||'').replace(/^technic-/,''));if(rules[id]||context.fixedCandidateIds.some(c=>c.startsWith('ov2:catalogId:'+encodeURIComponent(item.catalogId||item.id)+':quality:')))selected.push(item);}
  const snapshot=yield* global.MOEOptimizerV2Candidates.generateSteps({items:selected});
  const grouped=new Map(),filtered=[];n=0;
  for(const c of snapshot.candidates){yield {phase:'equivalence',processed:n++,total:snapshot.candidates.length};const row=global.MOEOptimizerV2Candidates.toEquipmentRow(c),source=snapshot.sources[c.sourceRef];const reason=global.MOEOptimizerV2EffectiveCandidates.filterReason(c,source,context);if(reason){filtered.push({candidateId:c.candidateId,reason});continue;}const r=rule(row);if(!r&&!fixed.has(c.candidateId))continue;
   const signature={slot:c.slot,pet:r,hand:row.weaponHand,twoHanded:optimizerWeaponUsesBothHands(row),projectile:projectileWeaponKind(row),ammo:optimizerAmmoKind(row),conflicts:optimizerEquipmentConflictKeys(row).sort(),fixed:fixed.has(c.candidateId)?c.candidateId:null};const key=JSON.stringify([context.objective,context.constraints,signature]);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(c);
  }
  const classes=[...grouped].map(([equivalenceKey,list])=>{list.sort((a,b)=>a.candidateId<b.candidateId?-1:1);return Object.freeze({equivalenceKey,equivalenceScope:'SearchContext',equipmentEquivalence:'not-assessed',observedMetrics:context.observations.metrics,representativeCandidate:list[0],representativeCandidateId:list[0].candidateId,equivalentCandidateIds:Object.freeze(list.map(c=>c.candidateId)),equivalentCandidates:Object.freeze(list),equivalenceReason:'identical-pet-group-and-legality'});});
  const fixedSlots=new Set();for(const id of fixed){const cls=classes.find(c=>c.representativeCandidateId===id);if(!cls)throw Error('固定装備が探索範囲にないか、装備条件を満たしていません。');const slot=cls.representativeCandidate.slot;if(fixedSlots.has(slot))throw Error('同じ部位に複数の装備を固定できません。');fixedSlots.add(slot);}
  const reduction={context,sources:snapshot.sources,candidates:classes.map(c=>c.representativeCandidate),contextEquivalentClasses:classes,equivalentClasses:classes,equivalentGroups:classes,filtered,removed:[],diagnostics:{afterFilterCount:classes.length}};
  return {snapshot,reduction,diagnostics:{input:items.length,relevant:classes.reduce((n,c)=>n+c.equivalentCandidates.length,0),classes:classes.length,petGrowth:true}};
 }
 global.MOEPetGrowth=Object.freeze({rules,rule,resolve,prepareBound,upper,prepareSteps});
})(globalThis);
